### ISSUE TITLE
翻墙速度好慢

### ISSUE THREAD

**Issue by luckypoem** [impakho/PyProxy#3]
hi。
装了你这个程序，但翻墙速度好慢。也许是没有加密造成的？
可以添加一层加密吗

**Comment by impakho** [comment]
翻墙速度与许多因素有关
脚本只是随便写写，你可以改一下

**Comment by luckypoem** [comment]
-:),我不会改。看看这个https://github.com/lerry/balan-proxy/ ，它也是两边各一个py文件，可能是有key机制，所以翻墙速度还可以。
